dependencies:
    - astropy
    - blaze-core
    - bokeh
    - bottleneck
    - click
    - cython
    - dask
    - decorator
    - freetype
    - gensim
    - h5py
    - hdf5
    - ipython
    - joblib
    - jupyter
    - libpng
    - libsodium
    - libtiff
    - libxml2
    - llvmlite
    - lz4
    - matplotlib
    - nltk
    - numba
    - numpy
    - pandas
    - pep8
    - pillow
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - sqlalchemy
    - sqlite
    - toolz
    - tornado
    - twisted
    - xray
    - pip:
        - awscli
        - bolt-python
        - certifi
        - deap
        - distributed
        - fbpca
        - keras
        - lasagne
        - mechanize
        - picos
        - plotly
        - pycallgraph
        - scikit-neuralnetwork
        - sima
        - spark-sklearn
        - tpot
        - tqdm
        - tweepy
