dependencies:
  - altair
  - astropy
  - awscli
  - bokeh
  - certifi
  - click
  - dask
  - deap
  - distributed
  - fastparquet
  - flask
  - freetype
  - joblib
  - keras
  - lasagne
  - libsodium
  - mxnet
  - opencv
  - pillow
  - plotly
  - protobuf
  - pyamg
  - scikit-image
  - seaborn
  - shapely
  - sqlite
  - theano
  - tpot
  - tqdm
  - tweepy
